FROM rockylinux:9.3

RUN dnf update -y && dnf install openssh-server sudo passwd -y

RUN groupadd sudo
RUN echo '%sudo ALL=(ALL:ALL) ALL' > /etc/sudoers.d/sudo

RUN adduser rockylinux
RUN usermod -aG sudo rockylinux

RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
RUN -p mkdir /run/sshd
RUN ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]