FROM debian:bookworm

RUN apt update && apt install openssh-server sudo passwd -y

RUN adduser debian
RUN usermod -aG sudo debian

RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
RUN mkdir -p /run/sshd
RUN ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]