FROM ubuntu:jammy

RUN apt update && apt install openssh-server sudo passwd -y

RUN adduser ubuntu
RUN usermod -aG sudo ubuntu

RUN sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
RUN mkdir -p /run/sshd
RUN ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]