FROM archlinux:base

RUN pacman -Syu --noconfirm && pacman -S --noconfirm openssh sudo

RUN groupadd sudo
RUN echo '%sudo ALL=(ALL:ALL) ALL' > /etc/sudoers

RUN useradd archlinux
RUN usermod -aG sudo archlinux

RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
RUN mkdir -p /run/sshd
RUN ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
