FROM ubuntu:jammy

RUN apt update && apt install openssh-server sudo passwd -y

RUN adduser ubuntu
RUN usermod -aG sudo ubuntu

RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
RUN mkdir -p /run/sshd
RUN ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]