FROM amazonlinux:2023

RUN dnf update -y && dnf install openssh-server sudo passwd -y

RUN groupadd sudo
RUN echo '%sudo ALL=(ALL:ALL) ALL' > /etc/sudoers.d/sudo

RUN adduser amazonlinux
RUN usermod -aG sudo amazonlinux

RUN mkdir /run/sshd
RUN ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

