FROM alpine:3.19.1

RUN apk update && apk add openssh-server sudo

RUN addgroup sudo
RUN echo '%sudo ALL=(ALL:ALL) ALL' > /etc/sudoers.d/sudo

RUN adduser -D alpine
RUN addgroup alpine sudo

RUN sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
RUN mkdir -p /run/sshd
RUN ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]