FROM almalinux:8

RUN dnf update -y && dnf install openssh-server sudo -y

RUN groupadd sudo
RUN echo '%sudo ALL=(ALL:ALL) ALL' > /etc/sudoers.d/sudo

RUN adduser almalinux
RUN usermod -aG sudo almalinux

RUN mkdir /run/sshd
RUN ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]